# Credit: https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
#
# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: generic

# Only clone the most recent commit.
git:
  depth: 1

# safelist
branches:
  only:
  - master

# Don't email me the results of the test runs.
notifications:
  email: false

services:
  - docker

env:
  - KUBECTL_VERSION=v1.12.10
  - KUBECTL_VERSION=v1.13.10
  - KUBECTL_VERSION=v1.14.6
  - KUBECTL_VERSION=v1.15.7
  - KUBECTL_VERSION=v1.16.4
  - KUBECTL_VERSION=v1.17.0

before_install:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  make build push KUBECTL_VERSION=${KUBECTL_VERSION}
